openapi: 3.0.2
info:
    title: 'Портал новостей OpenAPI'
    version: 0.0.1
servers:
    - url: http://127.0.0.1:8000/
    description: ''
paths:
  /news/:
    get:
      operationId: Список новостей/статей
      description: 'Список новостей/статьей'
      parameters: []
      responses:
        '200':
          content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/News'
          description: ''
      tags:
        - news

    post:
      operationId: Создание новости/статьи
      description: 'Создание новости/статьи'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News/create'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News/create'
          description: ''
      tags:
        - news

components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 64
      required:
        - name