# Generated by Django 4.2.1 on 2023-06-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
